name: Send Weekly Newsletter

on:
  schedule:
    - cron: '30 4 * * 1'  # Every Monday at 10:00 AM IST (4:30 AM UTC)
  workflow_dispatch:       # Optional: manual trigger

jobs:
  run-newsletter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up environment variables
        run: |
          echo "AZURE_OPENAI_API_KEY=${{ secrets.AZURE_OPENAI_API_KEY }}" >> $GITHUB_ENV
          echo "AZURE_OPENAI_ENDPOINT=${{ secrets.AZURE_OPENAI_ENDPOINT }}" >> $GITHUB_ENV
          echo "AZURE_OPENAI_API_VERSION=${{ secrets.AZURE_OPENAI_API_VERSION }}" >> $GITHUB_ENV
          echo "TO_EMAIL=${{ secrets.TO_EMAIL }}" >> $GITHUB_ENV
          echo "HEADSIN_PASSWORD=${{ secrets.HEADSIN_PASSWORD }}" >> $GITHUB_ENV

      - name: Run newsletter script
        run: python main.py
